import os
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from pathlib import Path
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split

os.environ.setdefault("CUDA_VISIBLE_DEVICES", "1")

class ResidualLSTM(nn.Module):
    def __init__(self, input_size=3, hidden_size=64, num_layers=1):
        super().__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        out, _ = self.lstm(x)
        return self.fc(out[:, -1, :])

def create_sequences(data, seq_length=10):
    xs, ys = [], []
    for i in range(len(data) - seq_length):
        x = data.iloc[i:i+seq_length][['soh_physics_baseline', 'r_internal_ohms', 'cycle']].values
        y = data.iloc[i+seq_length]['residual_target']
        xs.append(x)
        ys.append(y)
    return np.array(xs, dtype=np.float32), np.array(ys, dtype=np.float32)

def train_residual_lstm():
    base_dir = Path(__file__).parent.parent
    data_dir = base_dir / "data" / "nasa" / "processed"
    model_dir = base_dir / "soh" / "models"
    plot_dir = base_dir / "results" / "paper_plots"
    model_dir.mkdir(parents=True, exist_ok=True)
    plot_dir.mkdir(parents=True, exist_ok=True)

    batteries = ["B0005", "B0006", "B0007", "B0018"]

    # Load ECM parameters (generated by Step 4) to replace crude r_internal_ohms
    ecm_path = base_dir / "data" / "digital_twin_sets" / "ecm_parameters.csv"
    if ecm_path.exists():
        ecm_df = pd.read_csv(ecm_path)
        print("   Loaded ECM parameters for R0")
    else:
        ecm_df = None
        print("⚠️  ECM parameters not found (run Step 4 first); will use old r_internal_ohms")

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"🧠 Training SOH Residual LSTM on {device}")

    dfs = []
    for batt in batteries:
        fp = data_dir / f"{batt}_aging_features.csv"
        if not fp.exists():
            print(f"⚠️ {fp.name} not found. Run Step 2 first.")
            continue
        df = pd.read_csv(fp)
        # Merge ECM R0 if available
        if ecm_df is not None:
            batt_ecm = ecm_df[ecm_df['battery'] == batt][['cycle', 'r0_ohms']]
            df = df.merge(batt_ecm, on='cycle', how='left')
            if 'r0_ohms' in df.columns:
                df['r_internal_ohms'] = df['r0_ohms'].fillna(df['r_internal_ohms'])
                df.drop(columns=['r0_ohms'], inplace=True)
        # Normalise cycle number
        df['cycle'] = df['cycle'] / df['cycle'].max()
        dfs.append(df)

    if not dfs:
        print("❌ No data found. Aborting.")
        return

    X_all, y_all = [], []
    for df in dfs:
        X, y = create_sequences(df, seq_length=10)
        if len(X) > 0:
            X_all.append(X)
            y_all.append(y)

    X = np.concatenate(X_all)
    y = np.concatenate(y_all)
    print(f"   Combined dataset: {len(X)} sequences from {len(dfs)} batteries")

    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)
    print(f"   Train: {len(X_train)} | Val: {len(X_val)}")

    train_ds = TensorDataset(torch.from_numpy(X_train).to(device),
                             torch.from_numpy(y_train).reshape(-1,1).to(device))
    val_ds = TensorDataset(torch.from_numpy(X_val).to(device),
                           torch.from_numpy(y_val).reshape(-1,1).to(device))
    train_loader = DataLoader(train_ds, batch_size=16, shuffle=True)
    val_loader = DataLoader(val_ds, batch_size=64, shuffle=False)

    model = ResidualLSTM(input_size=3).to(device)
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=0.005)

    epochs = 100
    train_losses, val_losses = [], []

    for epoch in range(epochs):
        model.train()
        train_loss = 0.0
        for inputs, targets in train_loader:
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            loss.backward()
            optimizer.step()
            train_loss += loss.item() * inputs.size(0)
        train_loss /= len(train_ds)

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for inputs, targets in val_loader:
                outputs = model(inputs)
                loss = criterion(outputs, targets)
                val_loss += loss.item() * inputs.size(0)
        val_loss /= len(val_ds)

        train_losses.append(train_loss)
        val_losses.append(val_loss)
        if (epoch+1) % 10 == 0:
            print(f"Epoch [{epoch+1}/{epochs}], Train MSE: {train_loss:.6f}, Val MSE: {val_loss:.6f}")

    torch.save(model.state_dict(), model_dir / "lstm_residual_soh.pth")
    print("✅ Model saved.")

    fig, ax = plt.subplots(figsize=(10,6))
    ax.plot(range(1, epochs+1), train_losses, color='blue', label='Training Loss')
    ax.plot(range(1, epochs+1), val_losses, color='orange', label='Validation Loss')
    ax.set_xlabel('Epoch'); ax.set_ylabel('MSE Loss')
    ax.set_title('LSTM Residual SOH — Training & Validation Loss')
    ax.legend(); ax.grid(True, linestyle='--', alpha=0.6)
    plt.tight_layout()
    plt.savefig(str(plot_dir / 'lstm_training_loss.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print(f"📈 Loss curve saved.")

if __name__ == "__main__":
    train_residual_lstm()