"""
Step 5: Train Transformer for Core Temperature Estimation
==========================================================
Based on: "Hybrid Electrical Circuit Model and Deep Learning-Based Core
Temperature Estimation" (Samanta, Surya, Williamson et al., IEEE TTE 2022)

The paper uses a 2-D GLSTM; we use a Transformer Encoder (superior at
capturing thermal inertia via self-attention over temporal windows).

Input features (all from real experimental data + identified ECM params):
  - current_A          (real NASA measurement)
  - voltage_V          (real NASA measurement)
  - r0_ohms            (identified from real V-I per cycle)
  - temp_surface_C     (real NASA measurement)

Target:
  - temp_core_C_TARGET (generated by experimentally-tuned EETM physics model)

The physics model's core temperature is trustworthy because its surface
temperature output was calibrated to match the real measured surface temp
(UKS-style tuning in Step 4).
"""

import os
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from pathlib import Path
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split

os.environ.setdefault("CUDA_VISIBLE_DEVICES", "1")


class BatteryThermalTransformer(nn.Module):
    """
    Transformer Encoder for core temperature regression.
    
    Input:  [batch, seq_len, feature_dim]
    Output: [batch, 1]  (predicted core temperature at next timestep)
    """
    def __init__(self, feature_dim=4, d_model=128, nhead=4, num_layers=4,
                 dim_feedforward=256, dropout=0.1):
        super().__init__()
        self.embedding = nn.Linear(feature_dim, d_model)
        self.pos_encoding = nn.Parameter(torch.randn(1, 512, d_model) * 0.02)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model, nhead=nhead,
            dim_feedforward=dim_feedforward,
            dropout=dropout, batch_first=True
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        self.regression_head = nn.Sequential(
            nn.Linear(d_model, 32),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(32, 1),
        )

    def forward(self, src):
        # src: [B, T, F]
        x = self.embedding(src)
        T = x.size(1)
        x = x + self.pos_encoding[:, :T, :]
        x = self.transformer(x)
        # Use last timestep's representation
        x = x[:, -1, :]
        return self.regression_head(x)


def create_sliding_windows(df, window_size=60, stride=1):
    """
    Create sliding windows per-cycle (never cross cycle boundaries).
    """
    features = ['current_A', 'voltage_V', 'r0_ohms', 'temp_surface_C']
    target = 'temp_core_C_TARGET'

    X_all, y_all = [], []

    for _, grp in df.groupby(['battery', 'cycle']):
        if len(grp) <= window_size:
            continue
        data_arr = grp[features].values.astype(np.float32)
        target_arr = grp[target].values.astype(np.float32)

        for i in range(0, len(grp) - window_size, stride):
            X_all.append(data_arr[i: i + window_size])
            y_all.append(target_arr[i + window_size])

    return np.array(X_all), np.array(y_all)


def train_thermal_transformer():
    """
    Step 5: Train the Transformer on the experimentally-tuned Digital Twin data.
    Includes 80/20 train/val split (sklearn) and saves loss curves.
    """
    base_dir = Path(__file__).parent.parent
    data_dir = base_dir / "data" / "digital_twin_sets"
    model_dir = base_dir / "transformer" / "models"
    plot_dir = base_dir / "results" / "paper_plots"
    model_dir.mkdir(parents=True, exist_ok=True)
    plot_dir.mkdir(parents=True, exist_ok=True)

    # Load both NASA twin data AND EV validation data
    file_path = data_dir / "augmented_aging_twin_dataset.csv"
    ev_path = base_dir / "data" / "ev_validation_sets" / "ev_drive_cycle_dataset.csv"

    frames = []
    if file_path.exists():
        frames.append(pd.read_csv(file_path))
        print(f"   Loaded NASA twin data: {len(frames[-1])} rows")
    else:
        print(f"⚠️ Dataset not found: {file_path}. Run Step 4 first.")
        return

    if ev_path.exists():
        frames.append(pd.read_csv(ev_path))
        print(f"   Loaded EV drive-cycle data: {len(frames[-1])} rows")

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"🧠 Preparing training data on {device}...")

    df = pd.concat(frames, ignore_index=True)
    print(f"   Combined dataset: {len(df)} rows, {df['battery'].nunique()} batteries, "
          f"{df.groupby('battery')['cycle'].nunique().sum()} cycles")

    # --- Normalisation (per-feature z-score) ---
    norm_cols = ['current_A', 'voltage_V', 'r0_ohms', 'temp_surface_C',
                 'temp_core_C_TARGET']
    stats = {}
    for col in norm_cols:
        mu, sigma = df[col].mean(), df[col].std() + 1e-8
        stats[col] = (mu, sigma)
        df[col] = (df[col] - mu) / sigma

    # Use a smaller window for the NASA data (~18s sampling → 60 steps ≈ 18 min)
    # Adjust if the data is denser/sparser
    avg_pts_per_cycle = df.groupby(['battery', 'cycle']).size().mean()
    window_size = min(60, int(avg_pts_per_cycle * 0.3))
    window_size = max(10, window_size)
    print(f"   Window size: {window_size} (avg pts/cycle: {avg_pts_per_cycle:.0f})")

    X, y = create_sliding_windows(df, window_size=window_size, stride=1)
    print(f"✅ Generated {len(X)} sequences of length {window_size}")

    if len(X) == 0:
        print("⚠️ No valid sequences generated. Check data.")
        return

    # --- Train / Val split (80/20 via sklearn) ---
    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=0.2, random_state=42
    )
    print(f"   Train: {len(X_train)} | Val: {len(X_val)}")

    train_ds = TensorDataset(torch.from_numpy(X_train),
                             torch.from_numpy(y_train).unsqueeze(1))
    val_ds = TensorDataset(torch.from_numpy(X_val),
                           torch.from_numpy(y_val).unsqueeze(1))

    train_loader = DataLoader(train_ds, batch_size=128, shuffle=True,
                              num_workers=2, pin_memory=True)
    val_loader = DataLoader(val_ds, batch_size=256, shuffle=False,
                            num_workers=2, pin_memory=True)

    # --- Model (larger for better accuracy) ---
    model = BatteryThermalTransformer(
        feature_dim=4, d_model=128, nhead=4, num_layers=4,
        dim_feedforward=256, dropout=0.1
    ).to(device)

    criterion = nn.MSELoss()
    optimizer = optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=100)

    epochs = 100
    best_val_loss = float('inf')
    train_losses = []
    val_losses = []

    print(f"🚀 Training Transformer ({sum(p.numel() for p in model.parameters()):,} params) "
          f"on {device} for {epochs} epochs...")

    for epoch in range(1, epochs + 1):
        # --- Train ---
        model.train()
        train_loss = 0.0
        for bx, by in train_loader:
            bx, by = bx.to(device), by.to(device)
            optimizer.zero_grad()
            pred = model(bx)
            loss = criterion(pred, by)
            loss.backward()
            optimizer.step()
            train_loss += loss.item() * bx.size(0)
        train_loss /= len(train_ds)

        # --- Validate ---
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for bx, by in val_loader:
                bx, by = bx.to(device), by.to(device)
                pred = model(bx)
                val_loss += criterion(pred, by).item() * bx.size(0)
        val_loss /= len(val_ds)

        scheduler.step()

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), model_dir / "transformer_thermal_core.pth")

        if epoch % 10 == 0 or epoch == 1:
            # De-normalise loss for interpretable error
            _, sigma_tc = stats['temp_core_C_TARGET']
            rmse_real = np.sqrt(val_loss) * sigma_tc
            print(f"  Epoch [{epoch:2d}/{epochs}]  "
                  f"Train MSE={train_loss:.6f}  Val MSE={val_loss:.6f}  "
                  f"Val RMSE(°C)={rmse_real:.4f}")

    # Final report
    _, sigma_tc = stats['temp_core_C_TARGET']
    print(f"\n✅ Training Complete!")
    print(f"   Best Val MSE = {best_val_loss:.6f}  "
          f"(RMSE = {np.sqrt(best_val_loss) * sigma_tc:.4f} °C)")
    print(f"   Model saved to: transformer/models/transformer_thermal_core.pth")

    # Save normalisation stats for inference
    stats_df = pd.DataFrame(stats, index=['mean', 'std'])
    stats_df.to_csv(model_dir / "normalisation_stats.csv")
    print(f"   Normalisation stats saved to: transformer/models/normalisation_stats.csv")

    # ---- Plot Training & Validation Loss Curves ----
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.plot(range(1, epochs + 1), train_losses, color='blue', linewidth=1.5, label='Training Loss')
    ax.plot(range(1, epochs + 1), val_losses, color='orange', linewidth=1.5, label='Validation Loss')
    ax.set_xlabel('Epoch', fontsize=12)
    ax.set_ylabel('MSE Loss (normalised)', fontsize=12)
    ax.set_title('Transformer Core Temperature — Training & Validation Loss', fontsize=14)
    ax.legend(fontsize=11)
    ax.grid(True, linestyle='--', alpha=0.6)
    plt.tight_layout()
    plt.savefig(str(plot_dir / 'transformer_training_loss.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print(f"📈 Loss curve saved to results/paper_plots/transformer_training_loss.png")


if __name__ == "__main__":
    train_thermal_transformer()
